### ISSUE TITLE
Add todo's to a list

### ISSUE THREAD

**Issue by fmkarakus** [fmkarakus/list-prototype#5]
User will be able to add a todo item in a list that has been created and see the list on display.

### Repository

- [x] developed on a branch called `add`

### Handler

- [x] Create, inside `const listPrototype` object the `add` function that render the new elements of the list 

### listener

- [x] Add listeners for `button` on the list

### views

- [x] create, inside `const listPrototype` object the `DisplayTodos` function that render the new items of the list.
