### ISSUE TITLE
Delete a todo item from a list

### ISSUE THREAD

**Issue by fmkarakus** [fmkarakus/list-prototype#6]
User will be able delete items on the lists that has been created

### Repository

- [x] developed on a branch called `delete`

### Handler

- [x]  Create, the `delete` function  inside `const listPrototype` object that render the new elements of the list 

### listener

- [x] Add listeners for `delete icon` on the list item

### views

- [x] Edit the `renderList` function that render the new items of the list.
